export enum PublicRoutePath {
  Root = '/',
  Login = '/login',
  CadastrarSenha = '/cadastrar-senha/:codigo',
  ComandaPublica = '/comanda/publica/:idPublico',
}

export function getComandaPublicaPath(idPublico: string) {
  return PublicRoutePath.ComandaPublica.replace(
    ':idPublico',
    encodeURIComponent(idPublico),
  )
}

export enum PrivateRoutePath {
  Banner = '/banners',
  BannerAdicionar = '/banners/adicionar',
  BannerEditar = '/banners/editar',
  BannerEditarId = '/banners/editar/:id',
  BannerVisualizar = '/banners/visualizar',
  BannerVisualizarId = '/banners/visualizar/:id',
  LojaParceira = '/lojas-parceiras',
  LojaParceiraAdicionar = '/lojas-parceiras/adicionar',
  LojaParceiraEditar = '/lojas-parceiras/editar',
  LojaParceiraEditarId = '/lojas-parceiras/editar/:id',
  LojaParceiraVisualizar = '/lojas-parceiras/visualizar',
  LojaParceiraVisualizarId = '/lojas-parceiras/visualizar/:id',
  Empresa = '/cadastros/empresa',
  Usuario = '/cadastros/usuarios',
  UsuarioAdicionar = '/cadastros/usuarios/adicionar',
  UsuarioEditar = '/cadastros/usuarios/editar',
  UsuarioEditarId = '/cadastros/usuarios/editar/:id',
  UsuarioVisualizar = '/cadastros/usuarios/visualizar',
  UsuarioVisualizarId = '/cadastros/usuarios/visualizar/:id',
  MinhaConta = '/minha-conta',
  Comanda = '/vendas/comanda',
  ComandaAdicionar = '/vendas/comanda/adicionar',
  ComandaEditar = '/vendas/comanda/editar',
  ComandaEditarId = '/vendas/comanda/editar/:id',
  ComandaVisualizar = '/vendas/comanda/visualizar',
  ComandaVisualizarId = '/vendas/comanda/visualizar/:id',
  AtendimentoChat = '/atendimento/chat',
  AtendimentoNumero = '/atendimento/numero',
  Categoria = '/estoque/categoria',
  CategoriaAdicionar = '/estoque/categoria/adicionar',
  CategoriaEditar = '/estoque/categoria/editar',
  CategoriaEditarId = '/estoque/categoria/editar/:id',
  CategoriaVisualizar = '/estoque/categoria/visualizar',
  CategoriaVisualizarId = '/estoque/categoria/visualizar/:id',
  Peso = '/estoque/peso',
  PesoAdicionar = '/estoque/peso/adicionar',
  PesoEditar = '/estoque/peso/editar',
  PesoEditarId = '/estoque/peso/editar/:id',
  PesoVisualizar = '/estoque/peso/visualizar',
  PesoVisualizarId = '/estoque/peso/visualizar/:id',
  Tamanho = '/estoque/tamanho',
  TamanhoAdicionar = '/estoque/tamanho/adicionar',
  TamanhoEditar = '/estoque/tamanho/editar',
  TamanhoEditarId = '/estoque/tamanho/editar/:id',
  TamanhoVisualizar = '/estoque/tamanho/visualizar',
  TamanhoVisualizarId = '/estoque/tamanho/visualizar/:id',
  MovimentoProduto = '/estoque/movimentacao-produto',
  MovimentoProdutoAdicionar = '/estoque/movimentacao-produto/adicionar',
  Cliente = '/cadastros/clientes',
  ClienteAdicionar = '/cadastros/clientes/adicionar',
  ClienteEditar = '/cadastros/clientes/editar',
  ClienteEditarId = '/cadastros/clientes/editar/:id',
  ClienteVisualizar = '/cadastros/clientes/visualizar',
  ClienteVisualizarId = '/cadastros/clientes/visualizar/:id',
  ClienteUltimosPedidosCpf = '/vendas/cliente/ultimos-pedido-cpf',
  ClienteUltimosPedidosCnpj = '/vendas/cliente/ultimos-pedido-cnpj',
  Produto = '/cadastros/produtos',
  ProdutoAdicionar = '/cadastros/produtos/adicionar',
  ProdutoEditar = '/cadastros/produtos/editar',
  ProdutoEditarId = '/cadastros/produtos/editar/:id',
  ProdutoVisualizar = '/cadastros/produtos/visualizar',
  ProdutoVisualizarId = '/cadastros/produtos/visualizar/:id',
  TabelaDePreco = '/vendas/tabela-de-preco',
  TabelaDePrecoAdicionar = '/vendas/tabela-de-preco/adicionar',
  TabelaDePrecoEditar = '/vendas/tabela-de-preco/editar',
  TabelaDePrecoEditarId = '/vendas/tabela-de-preco/editar/:id',
  TabelaDePrecoVisualizar = '/vendas/tabela-de-preco/visualizar',
  TabelaDePrecoVisualizarId = '/vendas/tabela-de-preco/visualizar/:id',
  Estoque = '/estoque/posicao-estoque',
  EstoqueMovimentacao = '/estoque/posicao-estoque/editar',
  EstoqueMovimentacaoId = '/estoque/posicao-estoque/editar/:id',
  Bonificados = '/financeiro/bonificados',
  ContaAReceber = '/financeiro/contas-a-receber',
  Mensalidade = '/financeiro/mensalidades',
  MensalidadeVisualizar = '/financeiro/mensalidades/visualizar',
  MensalidadeVisualizarId = '/financeiro/mensalidades/visualizar/:id',
  TransacaoFinanceira = '/financeiro/transacoes',
  Dashboard = '/dashboard',
}

export enum AppRoutePath {
  Wildcard = '*',
}
