import type { Menu } from '../types/MenuTypes'

export const menus: Menu[] = [
  {
    id: 1,
    nome: 'Home',
    caminho: '/dashboard',
    icone: 'clarity:home-line',
    filhos: [],
  },
  {
    id: 2,
    nome: 'E-commerce',
    icone: 'icon-park-outline:shopping',
    filhos: [
      {
        id: 3,
        nome: 'Banners',
        caminho: '/banners',
        icone: 'material-symbols-light:planner-banner-ad-pt-outline',
        filhos: [],
      },
      {
        id: 4,
        nome: 'Lojas parceiras',
        caminho: '/lojas-parceiras',
        icone: 'mdi:store-check-outline',
        filhos: [],
      },
    ],
  },
  {
    id: 5,
    nome: 'Estoque',
    icone: 'healthicons:stock-out-outline',
    filhos: [
      {
        id: 6,
        nome: 'Categoria',
        caminho: '/estoque/categoria',
        icone: 'mdi:category-outline',
        filhos: [],
      },
      {
        id: 7,
        nome: 'Produto',
        caminho: '/estoque/produto',
        icone: 'fluent-mdl2:product-variant',
        filhos: [],
      },
      {
        id: 8,
        nome: 'Peso',
        caminho: '/estoque/peso',
        icone: 'game-icons:weight',
        filhos: [],
      },
      {
        id: 9,
        nome: 'Tamanho',
        caminho: '/estoque/tamanho',
        icone: 'bx:font-size',
        filhos: [],
      },
      {
        id: 10,
        nome: 'Movimento produto',
        caminho: '/estoque/movimentacao-produto',
        icone: 'arcticons:stockswidget',
        filhos: [],
      },
      {
        id: 11,
        nome: 'Posição estoque',
        caminho: '/estoque/posicao-estoque',
        icone: 'icon-park-outline:database-position',
        filhos: [],
      },
      {
        id: 12,
        nome: 'Relatórios',
        icone: 'mdi:report-finance',
        filhos: [
          {
            id: 13,
            nome: 'Posição de estoque',
            caminho: '/estoque/relatorio-posicao-estoque',
            icone: 'hugeicons:package-out-of-stock',
            filhos: [],
          },
          {
            id: 14,
            nome: 'Relatório de estoque',
            caminho: '/estoque/relatorio-estoque',
            icone: 'tabler:report-search',
            filhos: [],
          },
          {
            id: 15,
            nome: 'Relatório de produção',
            caminho: '/estoque/relatorio-producao',
            icone: 'simple-icons:soundcharts',
            filhos: [],
          },
        ],
      },
    ],
  },
  {
    id: 16,
    nome: 'Vendas',
    icone: 'carbon:sales-ops',
    filhos: [
      {
        id: 17,
        nome: 'Pedidos',
        caminho: '/pedidos',
        icone: 'material-symbols:order-approve-outline',
        filhos: [],
      },
      {
        id: 18,
        nome: 'Tabela de preço',
        caminho: '/vendas/tabeladepreco',
        icone: 'solar:tag-price-bold',
        filhos: [],
      },
      {
        id: 19,
        nome: 'Preço por peso',
        caminho: '/vendas/preco-por-peso',
        icone: 'material-symbols-light:price-change-outline-rounded',
        filhos: [],
      },
      {
        id: 20,
        nome: 'Preço por tamanho',
        caminho: '/vendas/preco-por-tamanho',
        icone: 'solar:tag-price-outline',
        filhos: [],
      },
      {
        id: 21,
        nome: 'Relatório por período',
        caminho: '/vendas/relatorio-por-periodo',
        icone: 'tabler:report-search',
        filhos: [],
      },
      {
        id: 22,
        nome: 'Relatório venda produto',
        caminho: '/vendas/relatorio-venda-produto',
        icone: 'fluent-mdl2:product-variant',
        filhos: [],
      },
      {
        id: 23,
        nome: 'Clientes',
        caminho: '/vendas/cliente',
        icone: 'solar:user-id-linear',
        filhos: [],
      },
    ],
  },
  {
    id: 24,
    nome: 'Configurações',
    icone: 'iwwa:settings',
    filhos: [
      {
        id: 25,
        nome: 'Minha empresa',
        caminho: '/configuracao/minha-empresa',
        icone: 'mdi:company',
        filhos: [],
      },
      {
        id: 26,
        nome: 'Pedidos',
        caminho: '/configuracao/pedido',
        icone: 'material-symbols:order-approve-outline',
        filhos: [],
      },
      {
        id: 27,
        nome: 'Mercado Pago',
        caminho: '/configuracao/mercado-pago',
        icone: 'simple-icons:mercadopago',
        filhos: [],
      },
      {
        id: 28,
        nome: 'Frete',
        caminho: '/configuracao/frete',
        icone: 'fluent:vehicle-truck-cube-24-regular',
        filhos: [],
      },
    ],
  },
  {
    id: 29,
    nome: 'Financeiro',
    icone: 'rivet-icons:money',
    filhos: [
      {
        id: 30,
        nome: 'Contas a receber',
        caminho: '/financeiro/contas-a-receber',
        icone: 'game-icons:receive-money',
        filhos: [],
      },
      {
        id: 31,
        nome: 'Contas a pagar',
        caminho: '/financeiro/contas-a-pagar',
        icone: 'game-icons:pay-money',
        filhos: [],
      },
      {
        id: 32,
        nome: 'Bonificados',
        caminho: '/financeiro/bonificados',
        icone: 'mdi:gift-outline',
        filhos: [],
      },
      {
        id: 33,
        nome: 'Transações',
        caminho: '/financeiro/transacao-financeira',
        icone: 'grommet-icons:transaction',
        filhos: [],
      },
      {
        id: 34,
        nome: 'Mensalidades',
        caminho: '/financeiro/cobranca',
        icone: 'hugeicons:payment-02',
        filhos: [],
      },
    ],
  },
]
